Update gas.yml

diff --git a/.github/workflows/gas.yml b/.github/workflows/gas.yml
--- a/.github/workflows/gas.yml
+++ b/.github/workflows/gas.yml
@@ -25,11 +25,11 @@ jobs:
             cd ${{ secrets.PROJECT_PATH }} || git clone ${{ secrets.REPO_URL }} ${{ secrets.PROJECT_PATH }};
             cd ${{ secrets.PROJECT_PATH }};
             git pull origin main;
-            pid=$(lsof -t -i:${{ secrets.PORT }}) && kill -9 $pid || true;
-            bun install || { echo 'Installation failed'; exit 1; }
-            bun run build || { echo 'Build failed'; exit 1; }
             rm -f .env
             echo '${{ secrets.ENV_VAR }}' > .env;
+            bun install || { echo 'Installation failed'; exit 1; }
+            bun run build || { echo 'Build failed'; exit 1; }
+            pid=$(lsof -t -i:${{ secrets.PORT }}) && kill -9 $pid || true;
             nohup bun run start -p ${{ secrets.PORT }} > app.log 2>&1 &
             echo 'Application started successfully'
           "
